services:
  rails:
    build:
      context: ./rails-app
      dockerfile: Dockerfile
    ports:
      - "${PORT_RAILS}:3000"
    depends_on:
      - db
    volumes:
      - ./rails-app:/app
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: ILoveDoingKnowBe4Training!
  db:
    image: postgres
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: ILoveDoingKnowBe4Training!
    ports:
      - "${PORT_POSTGRES}:5432"
